<div class="grid_16 suffix_1">
	<a href="/"><img alt="" src="/images/logo.png"/></a>
</div>
<div class="nav grid_15">
	<div class="grid_3 alpha aCenter "><a href="/">На главную</a></div>
	<div class="grid_3 alpha aCenter "><a href="/static/partners">Поставщикам</a></div>
	<div class="grid_3 aCenter "><a href="/static/faq">Помощь</a></div>
	<div class="grid_2 aCenter "><a href="/static/shipping">Доставка</a></div>
	<div class="grid_2 aCenter "><a href="/static/contactus">Контакты</a></div>
	<div class="grid_2 omega aCenter "><a href="/static/about">О нас</a></div>
</div>
<div class="clear"></div>