					<div style="font-size: 14px"><b><img src="/images/budvkurse.gif"/></b></div>
					<table style="border: 1px solid #D9D9D9; background-color: #ececec; margin-top: 10px">
						<tbody><tr>
							<td style="padding-top: 10px" align="center">
								<a target="_blank" href="http://twitter.com/1dayshop" onclick="_gaq.push(['_trackEvent','Keep in touch','Twitter']);" title="следить в твиттере"><img src="/images/tw.png"/></a>
							</td>
							<td style="padding-top: 10px" align="center">
								<a target="_blank" href="http://vkontakte.ru/club16981616" onclick="_gaq.push(['_trackEvent','Keep in touch','Vkontakte']);" title="следить в вконтакте"><img src="/images/vk.png"/></a> 
							</td>
							<!-- <td style="padding-top: 10px" align="center">
								<a target="_blank" href="" title=""><img src="/images/fa.png"/></a> 
							</td> -->
							<td style="padding-top: 10px" align="center">
								<a target="_blank" href="/rss/" onclick="_gaq.push(['_trackEvent','Keep in touch','RSS']);" title="следить через rss"><img src="/images/rs.png"/></a> 
							</td>
							<td style="font-size: 10px" width="70px" align="center">
							</td>
							<td style="padding-top: 10px" align="center">
							</td>
							<td style="padding-top: 10px" align="center">
								<a href="#" class="newsletterbox_open" title="подписаться на рассылку"><img src="/images/em.png"/></a> 
							</td>
						</tr>
						<tr>
							<td style="font-size: 10px;" width="70px" align="center">
								<a target="_blank" style="text-decoration: none" href="http://twitter.com/1dayshop" onclick="_gaq.push(['_trackEvent','Keep in touch','Twitter']);" title="следить в twitter">twitter</a>
							</td>
							<td style="font-size: 10px" width="70px" align="center">
								<a target="_blank" style="text-decoration: none" href="http://vkontakte.ru/club16981616" onclick="_gaq.push(['_trackEvent','Keep in touch','Vkontakte']);" title="следить в Вконтакте">Вконтакте</a>
							</td>
							<!-- <td style="font-size: 10px" width="70px" align="center">
								<a target="_blank" style="text-decoration: none" href="" title="следить в FaceBook">FaceBook</a>
							</td> -->
							<td style="font-size: 10px" width="70px" align="center">
								<a target="_blank" style="text-decoration: none" href="/rss/" onclick="_gaq.push(['_trackEvent','Keep in touch','RSS']);" title="следить через rss">RSS</a>
							</td>
							<td style="font-size: 10px" width="70px" align="center">
							</td>
							<td style="padding-top: 10px" width="100px" align="center">
							</td>
							<td style="font-size: 10px" width="70px" align="center">
								<a href="#" class="newsletterbox_open" style="text-decoration: none" title="подписаться на рассылку">Рассылка</a>
							</td>
						</tr>
					</tbody></table>
<div class="newsletter">
<input value="Ваш email..." class="input" type="text" id="mailing_email" size="25" maxlength="50"/>
<button>Подписаться</button>
</div>
