<div class="prefix_5 suffix_5 grid_22 pt30" style="padding-bottom: 1000px;">
		<div>
				<div class="cardcontent-upgrade" style="background-image: url(); width: 570px;">
					<div style="font-size: 16px;"><b>О проекте</b></div>
					<div style="padding-top: 10px;">1dayshop.com.ua - интернет-магазин и сообщество, которое стремится к тому, чтобы продавать дешевую интересную продукцию.</div>
					<div style="padding-top: 5px;">Каждый день на сайте 1dayshop.com.ua мы продаём только один товар по очень низкой цене. Кол-во продаваемого товара ограничено и поэтому всегда будут те, кто не успеет купить.</div>
					<div style="padding-top: 5px;">Почему у нас такая низкая цена? Каждый день мы продаем большой объем товара по оптовой цене. У нас простая логистика. У нас нет склада. У нас вообще все очень просто. Поэтому и дешево.</div>
					<div style="padding-top: 15px;">Мы являемся официальным партнёром интернет-магазина <a target="_blank" rel="nofollow" href="http://onedayshop.ru">onedayshop.ru</a>.</div>
				</div>
			</div>
<div class="clear"></div>
