<div class="prefix_5 suffix_5 grid_22 pt30" style="padding-bottom: 1000px;">
<div class="cardcontent-upgrade" style="background-image: url(); width: 650px;">
					<div style="font-size: 16px;"><b>Контактная информация</b></div><br/>

					<div style="padding-top: 10px;"><a href="mailto:info@1dayshop.com.ua" style="text-decoration: none;">info@1dayshop.com.ua</a> - по любым вопросам, включая вопросы сотрудничества и продажи товаров в нашем магазине</div>					
					<div style="padding-top: 15px;"><a href="mailto:admin@1dayshop.com.ua" style="text-decoration: none;">admin@1dayshop.com.ua</a> - по вопросам работы сайта</div>
				</div></div>
<div class="clear"></div>
