<div class="prefix_10 suffix_10 grid_12 pt30" style="padding-bottom: 1000px;">
					<div style="font-size: 16px;"><b>Доставка</b></div><br/>
					<div style="padding-top: 10px;">Курьером по Киеву — 30 грн.</div>
					<div style="padding-top: 5px;">Оплата производится наличными при получении товара.</div>
					<div style="padding-top: 5px;">Самовывоз — бесплатно.</div>
				</div>
				<div class="clear"></div>
