<?php

/**
 * Customer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Customer extends BaseCustomer
{
    public static function findByEmail($email) {
        $customer = Doctrine_Query::create()
             ->from('Customer c')
             ->where('c.email = ?',$email)
             ->fetchOne();
        if (null == $customer) {
            $customer = new Customer();
            $customer->email = $email;
        }
        return $customer;
    }
    
    //TODO Zend_Translate
    public function sendOrderNotification($order){
         $mail = new Zend_Mail('UTF-8');
         $mail->setBodyText("Добрый день,".$order->Customer->name."!\n\n\n Ваш заказ принят. Мы свяжемся с вами в ближайшее время\n Ваш магазин скидок,\n http://1dayshop.com.ua");
         $mail->setFrom('info@1dayshop.com.ua', '1dayshop.com.ua');
         $mail->addTo($order->Customer->email);
         //TODO: add admin
         $mail->addTo('info@1dayshop.com.ua');
         $mail->setSubject('Ваш заказ на '. $order->Product->name. ' принят');
         $mail->send();
    }
}