<div class="formItem">
	<input type="text" name="name" class="inputText" value="Ваше имя..."/>  
 	<label for="name" class="redText"><-- Как к Вам обращаться?</label>
</div>
<div class="formItem">
	<input type="text" name="phone" class="inputText" value="Ваш телефон..."/>  
 	<label for="phone" class="redText"><-- Это правильный номер?</label>
</div>
<div class="formItem">
	<input type="text" name="email" class="inputText" value="Ваш email..."/>  
 	<label for="email" class="redText"><-- Это правильный адрес?</label>
</div>
<div class="formItem">
	<a href="#" class="submit" onClick="ContactPop.submitForm();return(false);"><img src="/images/order.png"/></a>
</div>
